server:
  port: 2580
  servlet:
    context-path: /employee
    
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employeedb
  application:
    name: employee-example-rxjava
  main:
    allow-bean-definition-overriding: true
        
dbport: 27017
dbname: employeedb